struct UddsJsonProto {
    // 仅供 udds 内部使用的字段:
    string udds_comment;

    // 发布时间 (相对于发布者的 clock):
    unsigned long long send_timestamp_ns;
    // 接收时间 (相对于接收者的 clock):
    unsigned long long received_timestamp_ns;

    string robot_id;
    double x;
    double y;
    double theta;

    string json;
};
